# Generated by Django 5.0.3 on 2024-04-24 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careReceiver', '0002_initial'),
        ('caregiver', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caregivermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carerequestmodel',
            name='caregiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caregiver.caregivermodel'),
        ),
        migrations.AddField(
            model_name='carerequestmodel',
            name='carereceiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careReceiver.carereceivermodel'),
        ),
        migrations.AddField(
            model_name='caregivermodel',
            name='custom_unavailable_days',
            field=models.ManyToManyField(blank=True, related_name='customunavailableday', to='caregiver.customunavailabledaymodel', verbose_name='Dias indisponiveis'),
        ),
        migrations.AddField(
            model_name='caregivermodel',
            name='fixed_unavailable_days',
            field=models.ManyToManyField(blank=True, related_name='fixedunavailableday', to='caregiver.fixedunavailabledaymodel', verbose_name='Dias da semana indisponivel'),
        ),
        migrations.AddField(
            model_name='caregivermodel',
            name='fixed_unavailable_hours',
            field=models.ManyToManyField(blank=True, related_name='fixedunavailablehour', to='caregiver.fixedunavailablehourmodel', verbose_name='Horarios indisponiveis'),
        ),
        migrations.AddField(
            model_name='caregivermodel',
            name='qualifications',
            field=models.ManyToManyField(blank=True, related_name='qualifications', to='caregiver.qualificationmodel', verbose_name='Qualificações'),
        ),
        migrations.AddField(
            model_name='ratingmodel',
            name='care_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='caregiver.carerequestmodel'),
        ),
        migrations.AddField(
            model_name='caregivermodel',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='specialization', to='caregiver.specializationmodel', verbose_name='Especializações'),
        ),
        migrations.AddField(
            model_name='caregivermodel',
            name='work_exp',
            field=models.ManyToManyField(blank=True, related_name='workexperience', to='caregiver.workexperiencemodel', verbose_name='Experiencia de trabalho'),
        ),
    ]
