# Generated by Django 5.0.3 on 2024-05-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver', '0003_alter_carerequestmodel_id_alter_ratingmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedunavailablehourmodel',
            name='hour',
            field=models.SmallIntegerField(choices=[(0, 'Meia-noite'), (1, '1 hora'), (2, '2 horas'), (3, '3 horas'), (4, '4 horas'), (5, '5 horas'), (6, '6 horas'), (7, '7 horas'), (8, '8 horas'), (9, '9 horas'), (10, '10 horas'), (11, '11 horas'), (12, '12 horas'), (13, '13 horas'), (14, '14 horas'), (15, '15 horas'), (16, '16 horas'), (17, '17 horas'), (18, '18 horas'), (19, '19 horas'), (20, '20 horas'), (21, '21 horas'), (22, '22 horas'), (23, '23 horas')], verbose_name='Horario indisponivel'),
        ),
    ]
