# Generated by Django 5.0.3 on 2024-05-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver', '0004_alter_fixedunavailablehourmodel_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carerequestmodel',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
