# Generated by Django 5.0.3 on 2024-05-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver', '0005_alter_carerequestmodel_response_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carerequestmodel',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pendente'), (1, 'Recusado'), (2, 'Autorizado'), (3, 'Cancelado')]),
        ),
    ]
