# Generated by Django 5.0.3 on 2024-05-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver', '0006_alter_carerequestmodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='caregivermodel',
            name='career_time',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Anos de experiência'),
        ),
        migrations.AlterField(
            model_name='caregivermodel',
            name='custom_unavailable_days',
            field=models.ManyToManyField(blank=True, related_name='customunavailableday', to='caregiver.customunavailabledaymodel', verbose_name='Dias indisponíveis'),
        ),
        migrations.AlterField(
            model_name='caregivermodel',
            name='day_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Valor da diária'),
        ),
        migrations.AlterField(
            model_name='caregivermodel',
            name='fixed_unavailable_days',
            field=models.ManyToManyField(blank=True, related_name='fixedunavailableday', to='caregiver.fixedunavailabledaymodel', verbose_name='Dias da semana indisponíveis'),
        ),
        migrations.AlterField(
            model_name='caregivermodel',
            name='fixed_unavailable_hours',
            field=models.ManyToManyField(blank=True, related_name='fixedunavailablehour', to='caregiver.fixedunavailablehourmodel', verbose_name='Horários indisponíveis'),
        ),
        migrations.AlterField(
            model_name='caregivermodel',
            name='max_request_km',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Distância máxima de trabalho'),
        ),
        migrations.AlterField(
            model_name='caregivermodel',
            name='work_exp',
            field=models.ManyToManyField(blank=True, related_name='workexperience', to='caregiver.workexperiencemodel', verbose_name='Experiência de trabalho'),
        ),
        migrations.AlterField(
            model_name='customunavailabledaymodel',
            name='day',
            field=models.DateField(verbose_name='Dia indisponível'),
        ),
        migrations.AlterField(
            model_name='fixedunavailabledaymodel',
            name='day',
            field=models.SmallIntegerField(choices=[(0, 'Domingo'), (1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')], verbose_name='Dia da semana indisponível'),
        ),
        migrations.AlterField(
            model_name='fixedunavailablehourmodel',
            name='hour',
            field=models.SmallIntegerField(choices=[(0, 'Meia-noite'), (1, '1 hora'), (2, '2 horas'), (3, '3 horas'), (4, '4 horas'), (5, '5 horas'), (6, '6 horas'), (7, '7 horas'), (8, '8 horas'), (9, '9 horas'), (10, '10 horas'), (11, '11 horas'), (12, '12 horas'), (13, '13 horas'), (14, '14 horas'), (15, '15 horas'), (16, '16 horas'), (17, '17 horas'), (18, '18 horas'), (19, '19 horas'), (20, '20 horas'), (21, '21 horas'), (22, '22 horas'), (23, '23 horas')], verbose_name='Horário indisponível'),
        ),
        migrations.AlterField(
            model_name='workexperiencemodel',
            name='end_date',
            field=models.DateField(verbose_name='Data de saída'),
        ),
        migrations.AlterField(
            model_name='workexperiencemodel',
            name='start_date',
            field=models.DateField(verbose_name='Data de início'),
        ),
    ]
