# Generated by Django 5.0.3 on 2024-05-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver', '0007_customusermodel_alter_caregivermodel_career_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserModel',
        ),
        migrations.AlterField(
            model_name='caregivermodel',
            name='day_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da diária'),
        ),
        migrations.AlterField(
            model_name='caregivermodel',
            name='hour_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da hora'),
        ),
    ]
