# Generated by Django 5.0.3 on 2024-04-24 20:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareReceiverModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_contact', models.CharField(max_length=15, verbose_name='Telefone de Emergência')),
                ('share_special_care', models.BooleanField(default=False, verbose_name='Compartilhar Cuidados Especiais')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Informações Adicionais')),
            ],
            options={
                'verbose_name': 'Care Receiver',
                'verbose_name_plural': 'Care Receivers',
            },
        ),
        migrations.CreateModel(
            name='SpecialCareModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.IntegerField(choices=[(0, 'Cuidados com a Saúde'), (1, 'Apoio Emocional'), (2, 'Fisioterapia'), (3, 'Acompanhamento Médico'), (4, 'Apoio à Mobilidade'), (5, 'Cuidados Pessoais'), (6, 'Apoio Doméstico'), (7, 'Nutrição'), (8, 'Atividades Recreativas'), (9, 'Gestão de Demência/Alzheimer'), (10, 'Suporte Noturno'), (11, 'Gestão da Dor'), (12, 'Cuidados Paliativos')])),
            ],
        ),
        migrations.CreateModel(
            name='SpecialCareUserModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
    ]
