# Generated by Django 5.0.3 on 2024-04-24 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careReceiver', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carereceivermodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='care_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialcareusermodel',
            name='care_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_care_users', to='careReceiver.carereceivermodel'),
        ),
        migrations.AddField(
            model_name='specialcareusermodel',
            name='care_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_care_users', to='careReceiver.specialcaremodel'),
        ),
    ]
