# Generated by Django 5.0.3 on 2024-05-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customusermodel_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
