# Generated by Django 5.0.3 on 2024-03-08 20:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUnavailableDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('day', models.DateField(verbose_name='Dia indisponivel')),
            ],
            options={
                'verbose_name_plural': 'Unavailable days',
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='FixedUnavailableDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('day', models.SmallIntegerField(choices=[(0, 'Domingo'), (1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')], verbose_name='Dia da semana indisponivel')),
            ],
            options={
                'verbose_name_plural': 'Unavailable week days',
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='FixedUnavailableHour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('hour', models.SmallIntegerField(choices=[(0, 'Meia-noite'), (1, '1 hora'), (2, '2 horas'), (3, '3 horas'), (4, '4 horas'), (5, '5 horas'), (6, '6 horas'), (7, '7 horas'), (8, '8 horas'), (9, '9 horas'), (10, '10 horas'), (11, '11 horas'), (13, '13 horas'), (14, '14 horas'), (15, '15 horas'), (16, '16 horas'), (17, '17 horas'), (18, '18 horas'), (19, '19 horas'), (20, '20 horas'), (21, '21 horas'), (22, '22 horas'), (23, '23 horas')], verbose_name='Horario indisponivel')),
            ],
            options={
                'verbose_name_plural': 'Unavailable hours',
                'ordering': ['hour'],
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('conclusion_date', models.DateField(verbose_name='Data de conclusão')),
                ('file', models.TextField(blank=True, null=True, verbose_name='Link do comprovante de conclusão')),
            ],
            options={
                'verbose_name_plural': 'Qualifications',
                'ordering': ['conclusion_date'],
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.SmallIntegerField(choices=[(0, 'Fisioterapia Gerontológica'), (1, 'Cuidados Geriátricos')], verbose_name='Especialização')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('place', models.CharField(max_length=128, verbose_name='Local')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('start_date', models.DateField(verbose_name='Data de inicio')),
                ('end_date', models.DateField(verbose_name='Data de saida')),
            ],
            options={
                'verbose_name_plural': 'Work Experiences',
                'ordering': ['end_date'],
            },
        ),
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('hour_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor da hora')),
                ('day_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Valor da diaria')),
                ('max_request_km', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Distancia maxima de trabalho')),
                ('career_time', models.PositiveSmallIntegerField(default=0, verbose_name='Anos de experiencia')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Informações adicionais')),
                ('custom_unavailable_days', models.ManyToManyField(blank=True, related_name='customunavailableday', to='core.customunavailableday', verbose_name='Dias indisponiveis')),
                ('fixed_unavailable_days', models.ManyToManyField(blank=True, related_name='fixedunavailableday', to='core.fixedunavailableday', verbose_name='Dias da semana indisponivel')),
                ('fixed_unavailable_hours', models.ManyToManyField(blank=True, related_name='fixedunavailablehour', to='core.fixedunavailablehour', verbose_name='Horarios indisponiveis')),
                ('qualifications', models.ManyToManyField(blank=True, related_name='qualifications', to='core.qualification', verbose_name='Qualificações')),
                ('specializations', models.ManyToManyField(blank=True, related_name='specialization', to='core.specialization', verbose_name='Especializações')),
                ('work_exp', models.ManyToManyField(blank=True, related_name='workexperience', to='core.workexperience', verbose_name='Experiencia de trabalho')),
            ],
            options={
                'verbose_name_plural': 'Caregivers',
            },
        ),
    ]
