# Generated by Django 5.0.3 on 2024-03-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customunavailableday_fixedunavailableday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.SmallIntegerField(choices=[(0, 'Cuidados Básicos de Saúde'), (1, 'Apoio à Mobilidade'), (2, 'Higiene e Cuidados Pessoais'), (3, 'Nutrição e Preparo de Refeições'), (4, 'Estimulação Cognitiva e Emocional'), (5, 'Acompanhamento e Transporte'), (6, 'Gestão de Rotinas e Medicamentos'), (7, 'Cuidados com o Ambiente Doméstico'), (8, 'Suporte em Cuidados Paliativos'), (9, 'Formação em Demência e Alzheimer')], verbose_name='Especialização'),
        ),
    ]
