# Generated by Django 5.0.3 on 2024-04-12 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customusermodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carereceivermodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='care_receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
